// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lklqodxxlcndqkhldzsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrbHFvZHh4bGNuZHFraGxkenN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzQ5OTgsImV4cCI6MjA2NzYxMDk5OH0.lPwgIvNh6Fb7mfSR7N7ftHwUyk2LfcMzEBwZiclrIQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});